export type Category =
  | "painting"
  | "sculpture"
  | "photography"
  | "illustration"
  | "ceramics"
  | "intangible"

export interface Product {
  id: string
  reelId: string
  name: string
  description: string
  price: number
  imageUrl: string
  stock: number
  type: "print" | "original" | "goods" | "class"
}

export interface Artist {
  id: string
  name: string
  handle: string
  avatarUrl: string
  bio: string
  followers: number
}

export interface Reel {
  id: string
  artist: Artist
  title: string
  description: string
  category: Category
  tags: string[]
  videoId: string
  thumbnailUrl: string
  fundingProgress: number
  fundingGoal: number
  totalFunded: number
  duration: string
  createdAt: string
}

export const CATEGORY_OPTIONS = [
  { id: "painting",     label: "회화",     emoji: "🎨" },
  { id: "sculpture",    label: "조각",     emoji: "🗿" },
  { id: "photography",  label: "사진",     emoji: "📷" },
  { id: "illustration", label: "일러스트", emoji: "✏️" },
  { id: "ceramics",     label: "도예",     emoji: "🏺" },
  { id: "intangible", label: "무형예술", emoji: "🎭" },
  { id: "music",        label: "음악",     emoji: "🎵" },
  { id: "stationery", label: "문구/굿즈", emoji: "✏️" },
  { id: "fashion", label: "패션/쥬얼리", emoji: "👗" },
] as const

export const ARTISTS: Artist[] = [
  {
    id: "a1",
    name: "이선율",
    handle: "@seonul.art",
    avatarUrl: "https://i.pravatar.cc/150?img=1",
    bio: "붓 터치 한 겹마다 쌓이는 감정을 기록하는 화가. 겹쳐진 시간 속 인간의 내면을 탐구합니다.",
    followers: 14200,
  },
  {
    id: "a2",
    name: "비비(BiBi)",
    handle: "@bibi_art",
    avatarUrl: "https://i.pravatar.cc/150?img=2",
    bio: "작은 비즈 알갱이로 거대한 점묘화를 완성합니다. 인내와 색채가 만나는 순간을 기록합니다.",
    followers: 9800,
  },
  {
    id: "a3",
    name: "샌드맨",
    handle: "@sandman_art",
    avatarUrl: "https://i.pravatar.cc/150?img=3",
    bio: "파도가 가져가기 전, 모래 위에 새기는 찰나의 입체 예술. 사라짐 자체가 작품입니다.",
    followers: 31500,
  },
  {
    id: "a4",
    name: "목(木)공",
    handle: "@mokgong",
    avatarUrl: "https://i.pravatar.cc/150?img=4",
    bio: "거친 나무토막에서 부드러운 곡선을 찾아냅니다. 나무의 숨결을 손끝으로 전달하는 목공예가.",
    followers: 7300,
  },
  {
    id: "a5",
    name: "신하늘",
    handle: "@shinhaneul",
    avatarUrl: "https://i.pravatar.cc/150?img=5",
    bio: "18세의 눈으로 포착한 도시의 고요한 찰나. 청춘의 시선이 담긴 필름 사진작가.",
    followers: 22100,
  },
  {
    id: "a6",
    name: "김루피",
    handle: "@kim_luffy",
    avatarUrl: "https://i.pravatar.cc/150?img=6",
    bio: "중학생의 발걸음이 머무는 일상 속 작은 변화를 찾습니다. 변화를 렌즈에 담는 청소년 사진가.",
    followers: 5600,
  },
  {
    id: "a7",
    name: "달콤한 하루",
    handle: "@sweetday",
    avatarUrl: "https://i.pravatar.cc/150?img=7",
    bio: "한 스쿱의 달콤함에 색채의 마법을 담는 일러스트레이터. 일상의 달콤한 순간을 그립니다.",
    followers: 41800,
  },
  {
    id: "a8",
    name: "픽셀덕",
    handle: "@pixelduck",
    avatarUrl: "https://i.pravatar.cc/150?img=8",
    bio: "꿈속을 유영하는 캐릭터와 포근한 판타지 세계관을 픽셀로 만들어가는 디지털 아티스트.",
    followers: 18700,
  },
  {
    id: "a9",
    name: "아토(Ato)",
    handle: "@ato_art",
    avatarUrl: "https://i.pravatar.cc/150?img=9",
    bio: "차가운 흙에 생명력을 불어넣는 도예가. 어린 새 조각에 자유로운 비행의 꿈을 담습니다.",
    followers: 8400,
  },
  {
    id: "a10",
    name: "도공 김씨",
    handle: "@dogong",
    avatarUrl: "https://i.pravatar.cc/150?img=10",
    bio: "물레 위 흙이 형태를 갖춰가는 명상적인 순간. 손끝의 정교한 움직임으로 그릇을 빚습니다.",
    followers: 11200,
  },
  {
    id: "a11",
    name: "해금소녀",
    handle: "@haegeum_girl",
    avatarUrl: "https://i.pravatar.cc/150?img=11",
    bio: "두 줄의 현에서 피어나는 애달프고 맑은 선율. 해금으로 마음의 지도를 그리는 연주자.",
    followers: 26300,
  },
  {
    id: "a12",
    name: "줄광대",
    handle: "@julgwangdae",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
    bio: "땅과 하늘 사이, 긴장감 넘치는 우리 가락의 몸짓. 줄 위에서 전통의 숨결을 잇습니다.",
    followers: 15900,
    },
  {
    id: "a13",
    name: "멜로디 킴",
    handle: "@melody_piano",
    avatarUrl: "https://i.pravatar.cc/150?img=13",
    bio: "피아노 선율로 위로를 전합니다. 클래식부터 뉴에이지까지 폭넓은 연주를 들려드려요.",
    followers: 12000,
  },
  {
    id: "a14",
    name: "바이올린 퀸",
    handle: "@violin_queen",
    avatarUrl: "https://i.pravatar.cc/150?img=14",
    bio: "열정적인 바이올린 연주로 무대를 압도합니다. 콩쿨 준비 과정과 연주 영상을 공유해요.",
    followers: 45000,
  },
  {
    id: "a15",
    name: "스톤메이커",
    handle: "@stonemaker",
    avatarUrl: "https://i.pravatar.cc/150?img=15",
    bio: "불안을 덜어주는 워리스톤을 만듭니다. 손끝에서 느껴지는 매끄러운 평온함을 선물하세요.",
    followers: 8200,
  },
  {
    id: "a16",
    name: "드레스 마스터",
    handle: "@dress_master",
    avatarUrl: "https://i.pravatar.cc/150?img=16",
    bio: "일상의 소재로 마법 같은 드레스를 만듭니다. 업사이클링 패션의 가능성을 보여드려요.",
    followers: 67000,
  },
  {
    id: "a17",
    name: "그린 젬",
    handle: "@green_gem",
    avatarUrl: "https://i.pravatar.cc/150?img=17",
    bio: "버려진 유리병을 보석으로 바꿉니다. 지속 가능한 주얼리를 연구하는 공예가.",
    followers: 15400,
  },
]

export const REELS: Reel[] = [
  {
    id: "r1",
    artist: ARTISTS[0],
    title: "겹쳐진 시간의 얼굴",
    description: "붓 터치 한 겹마다 쌓이는 인간의 다채로운 감정 기록",
    category: "painting",
    tags: ["회화", "감정", "레이어링", "인물화"],
    videoId: "jL27lgh6Jt0",
    thumbnailUrl: "https://img.youtube.com/vi/jL27lgh6Jt0/maxresdefault.jpg",
    fundingProgress: 78,
    fundingGoal: 500000,
    totalFunded: 390000,
    duration: "1:12",
    createdAt: "2024-03-15",
  },
  {
    id: "r2",
    artist: ARTISTS[1],
    title: "구슬로 빚은 우주",
    description: "작은 비즈 알이 모여 하나의 거대한 점묘화가 되는 순간",
    category: "painting",
    tags: ["비즈", "점묘화", "우주", "인내"],
    videoId: "_ABKwksUAdo",
    thumbnailUrl: "https://img.youtube.com/vi/_ABKwksUAdo/maxresdefault.jpg",
    fundingProgress: 54,
    fundingGoal: 800000,
    totalFunded: 432000,
    duration: "0:58",
    createdAt: "2024-03-10",
  },
  {
    id: "r3",
    artist: ARTISTS[2],
    title: "파도가 빌려간 성",
    description: "썰물이 오기 전까지만 허락된 찰나의 입체 예술",
    category: "sculpture",
    tags: ["모래조각", "해변", "찰나", "자연미술"],
    videoId: "yLlXgGuG2gI",
    thumbnailUrl: "https://img.youtube.com/vi/yLlXgGuG2gI/maxresdefault.jpg",
    fundingProgress: 91,
    fundingGoal: 300000,
    totalFunded: 273000,
    duration: "1:35",
    createdAt: "2024-03-08",
  },
  {
    id: "r4",
    artist: ARTISTS[3],
    title: "나무의 숨결을 깎다",
    description: "거친 나무토막에서 부드러운 곡선의 오브제를 찾는 과정",
    category: "sculpture",
    tags: ["목공예", "나무", "조각", "수공예"],
    videoId: "S2zU2IVCrMw",
    thumbnailUrl: "https://img.youtube.com/vi/S2zU2IVCrMw/maxresdefault.jpg",
    fundingProgress: 43,
    fundingGoal: 600000,
    totalFunded: 258000,
    duration: "1:08",
    createdAt: "2024-03-01",
  },
  {
    id: "r5",
    artist: ARTISTS[4],
    title: "18세의 푸른 소음",
    description: "고등학생의 시선으로 담아낸 도시의 가장 고요한 찰나",
    category: "photography",
    tags: ["필름사진", "청춘", "도시", "고요함"],
    videoId: "cnWtgL12psw",
    thumbnailUrl: "https://img.youtube.com/vi/cnWtgL12psw/maxresdefault.jpg",
    fundingProgress: 86,
    fundingGoal: 200000,
    totalFunded: 172000,
    duration: "0:44",
    createdAt: "2024-02-28",
  },
  {
    id: "r6",
    artist: ARTISTS[5],
    title: "렌즈로 본 '변화'",
    description: "중학생의 발걸음이 머무는 일상 속 작은 변화들 찾기",
    category: "photography",
    tags: ["다큐멘터리", "일상", "변화", "청소년"],
    videoId: "594ySuwufGw",
    thumbnailUrl: "https://img.youtube.com/vi/594ySuwufGw/maxresdefault.jpg",
    fundingProgress: 37,
    fundingGoal: 150000,
    totalFunded: 55500,
    duration: "0:51",
    createdAt: "2024-02-20",
  },
  {
    id: "r7",
    artist: ARTISTS[6],
    title: "녹지 않는 여름, 젤라또",
    description: "한 스쿱의 달콤함에 담긴 색채의 마법",
    category: "illustration",
    tags: ["일러스트", "젤라또", "여름", "색채"],
    videoId: "crBIAFOE9M4",
    thumbnailUrl: "https://img.youtube.com/vi/crBIAFOE9M4/maxresdefault.jpg",
    fundingProgress: 95,
    fundingGoal: 120000,
    totalFunded: 114000,
    duration: "0:37",
    createdAt: "2024-02-15",
  },
  {
    id: "r8",
    artist: ARTISTS[7],
    title: "소녀의 어느 여름날",
    description: "꿈속을 유영하는 캐릭터의 포근한 판타지 세계관",
    category: "illustration",
    tags: ["픽셀아트", "판타지", "캐릭터", "여름"],
    videoId: "3uHmC0DgFCg",
    thumbnailUrl: "https://img.youtube.com/vi/3uHmC0DgFCg/maxresdefault.jpg",
    fundingProgress: 62,
    fundingGoal: 250000,
    totalFunded: 155000,
    duration: "0:29",
    createdAt: "2024-02-10",
  },
  {
    id: "r9",
    artist: ARTISTS[8],
    title: "흙으로 빚은 비행",
    description: "차가운 흙에 생명력을 불어넣어 만든 어린 새 조각",
    category: "ceramics",
    tags: ["도예", "새조각", "생명", "흙"],
    videoId: "AQGXPr0CtnM",
    thumbnailUrl: "https://img.youtube.com/vi/AQGXPr0CtnM/maxresdefault.jpg",
    fundingProgress: 71,
    fundingGoal: 400000,
    totalFunded: 284000,
    duration: "1:20",
    createdAt: "2024-02-05",
  },
  {
    id: "r10",
    artist: ARTISTS[9],
    title: "물레 위에서 춤추는 손",
    description: "흙이 형태를 갖춰가는 명상적이고 정교한 손놀림",
    category: "ceramics",
    tags: ["도예", "물레", "명상", "손"],
    videoId: "fiOP2ni4CdE",
    thumbnailUrl: "https://img.youtube.com/vi/fiOP2ni4CdE/maxresdefault.jpg",
    fundingProgress: 49,
    fundingGoal: 350000,
    totalFunded: 171500,
    duration: "0:55",
    createdAt: "2024-01-30",
  },
  {
    id: "r11",
    artist: ARTISTS[10],
    title: "두 줄의 대화, 해금",
    description: "애달프면서도 맑은 해금 선율이 그리는 마음의 지도",
    category: "intangible",
    tags: ["해금", "국악", "무형문화재", "선율"],
    videoId: "8pQb77iGOXw",
    thumbnailUrl: "https://img.youtube.com/vi/8pQb77iGOXw/maxresdefault.jpg",
    fundingProgress: 83,
    fundingGoal: 700000,
    totalFunded: 581000,
    duration: "2:04",
    createdAt: "2024-01-25",
  },
  {
    id: "r12",
    artist: ARTISTS[11],
    title: "하늘 위에서 걷는 법",
    description: "땅과 하늘 사이, 긴장감 넘치는 우리 가락의 몸짓",
    category: "intangible",
    tags: ["줄타기", "전통공연", "무형유산", "국악"],
    videoId: "_5wZxhwRNBQ",
    thumbnailUrl: "https://img.youtube.com/vi/_5wZxhwRNBQ/maxresdefault.jpg",
    fundingProgress: 66,
    fundingGoal: 1000000,
    totalFunded: 660000,
    duration: "1:47",
    createdAt: "2024-01-20",
    },
  {
    id: "r13",
    artist: ARTISTS.find(a => a.id === "a13")!,
    title: "His Theme 연주",
    description: "오늘은 히스 테마라는 곡을 연주해보았어요. 선율이 참 아름다운 노래입니다 ~^^",
    category: "music",
    tags: ["피아노", "HisTheme", "뉴에이지", "연주"],
    videoId: "sopEVuNv4gw",
    thumbnailUrl: "https://img.youtube.com/vi/sopEVuNv4gw/maxresdefault.jpg",
    fundingProgress: 45,
    fundingGoal: 500000,
    totalFunded: 225000,
    duration: "0:59",
    createdAt: "2024-04-01",
  },
  {
    id: "r14",
    artist: ARTISTS.find(a => a.id === "a14")!,
    title: "파가니니의 라캄파넬라",
    description: "콩쿨에서 라캄파넬라 연주를 성공했어요! 연습한 보람이 느껴지는 순간입니다.",
    category: "music",
    tags: ["바이올린", "라캄파넬라", "파가니니", "콩쿨"],
    videoId: "OYyGvD_-8OM",
    thumbnailUrl: "https://img.youtube.com/vi/OYyGvD_-8OM/maxresdefault.jpg",
    fundingProgress: 92,
    fundingGoal: 1000000,
    totalFunded: 920000,
    duration: "0:58",
    createdAt: "2024-04-05",
  },
  {
    id: "r15",
    artist: ARTISTS.find(a => a.id === "a15")!,
    title: "마음의 평온, 워리스톤 제작기",
    description: "불안을 다스리는 작고 소중한 돌, 워리스톤을 깎고 다듬는 힐링 과정입니다.",
    category: "stationery",
    tags: ["워리스톤", "핸드메이드", "힐링", "굿즈"],
    videoId: "K70fvlto-To",
    thumbnailUrl: "https://img.youtube.com/vi/K70fvlto-To/maxresdefault.jpg",
    fundingProgress: 68,
    fundingGoal: 300000,
    totalFunded: 204000,
    duration: "0:52",
    createdAt: "2024-04-10",
  },
  {
    id: "r16",
    artist: ARTISTS.find(a => a.id === "a16")!,
    title: "5000원의 무도회",
    description: "다이소 발매트로 중세 드레스 만들기! 저렴한 소재의 놀라운 변신을 확인하세요.",
    category: "fashion",
    tags: ["업사이클링", "드레스제작", "DIY", "코스튬"],
    videoId: "KOpQ0sQiNNs",
    thumbnailUrl: "https://img.youtube.com/vi/KOpQ0sQiNNs/maxresdefault.jpg",
    fundingProgress: 88,
    fundingGoal: 400000,
    totalFunded: 352000,
    duration: "10:15",
    createdAt: "2024-04-12",
  },
  {
    id: "r17",
    artist: ARTISTS.find(a => a.id === "a17")!,
    title: "다시 태어난 초록빛",
    description: "테라병을 업사이클링하여 목걸이로 제작하는 방법, 버려지는 것들에 재발견",
    category: "fashion",
    tags: ["주얼리공예", "유리공예", "에코패션", "목걸이"],
    videoId: "-g1_NzYWlQA",
    thumbnailUrl: "https://img.youtube.com/vi/-g1_NzYWlQA/maxresdefault.jpg",
    fundingProgress: 75,
    fundingGoal: 200000,
    totalFunded: 150000,
    duration: "8:42",
    createdAt: "2024-04-15",
  },
]

export const PRODUCTS: Product[] = [
  // 회화 (r1 - 이선율)
  {
    id: "p1",
    reelId: "r1",
    name: "A4 아트프린트 — 겹쳐진 시간의 얼굴",
    description: "이선율 작가의 대표작을 고품질 아트지에 인쇄한 프린트입니다.",
    price: 3000,
    imageUrl: "https://picsum.photos/seed/p1/300/300",
    stock: 30,
    type: "print",
  },
  {
    id: "p2",
    reelId: "r1",
    name: "원본 캔버스 소품 (10×10cm)",
    description: "작가가 직접 그린 소형 캔버스 원본 작품입니다. 사인 포함.",
    price: 50000,
    imageUrl: "https://picsum.photos/seed/p2/300/300",
    stock: 1,
    type: "original",
  },
  // 회화 (r2 - 비비)
  {
    id: "p3",
    reelId: "r2",
    name: "비즈 우주 스티커팩 (10종)",
    description: "구슬로 빚은 우주 작품을 스티커로 만났어요. 방수 코팅 처리.",
    price: 1500,
    imageUrl: "https://picsum.photos/seed/p3/300/300",
    stock: 50,
    type: "goods",
  },
  // 조각 (r3 - 샌드맨)
  {
    id: "p4",
    reelId: "r3",
    name: "모래성 포토카드 세트 (5종)",
    description: "파도가 빌려간 성 촬영본을 엽서 포토카드로. 각 작품별 인쇄.",
    price: 1000,
    imageUrl: "https://picsum.photos/seed/p4/300/300",
    stock: 100,
    type: "goods",
  },
  // 조각 (r4 - 목공)
  {
    id: "p5",
    reelId: "r4",
    name: "미니 목공예 오브제",
    description: "나무의 숨결을 담은 작가 직접 제작 소품. 각 작품마다 형태가 다릅니다.",
    price: 12000,
    imageUrl: "https://picsum.photos/seed/p5/300/300",
    stock: 5,
    type: "original",
  },
  // 사진 (r5 - 신하늘)
  {
    id: "p6",
    reelId: "r5",
    name: "필름 포토카드 세트 (6종)",
    description: "18세의 눈으로 담은 도시의 고요함. 필름 질감 인쇄 포토카드.",
    price: 1500,
    imageUrl: "https://picsum.photos/seed/p6/300/300",
    stock: 80,
    type: "goods",
  },
  {
    id: "p7",
    reelId: "r5",
    name: "A3 사진 프린트 — 18세의 푸른 소음",
    description: "고해상도 무광 아트지 인쇄. 직접 프레임에 넣어 걸 수 있어요.",
    price: 4000,
    imageUrl: "https://picsum.photos/seed/p7/300/300",
    stock: 20,
    type: "print",
  },
  // 사진 (r6 - 김루피)
  {
    id: "p8",
    reelId: "r6",
    name: "일상 기록 포토카드 세트 (4종)",
    description: "중학생의 시선으로 포착한 변화의 순간들을 포토카드로 담았습니다.",
    price: 1000,
    imageUrl: "https://picsum.photos/seed/p8/300/300",
    stock: 60,
    type: "goods",
  },
  // 일러스트 (r7 - 달콤한 하루)
  {
    id: "p9",
    reelId: "r7",
    name: "젤라또 일러스트 스티커팩 (12종)",
    description: "달콤한 여름 젤라또 시리즈를 스티커로. 다이어리, 컵, 노트북에 딱!",
    price: 1000,
    imageUrl: "https://picsum.photos/seed/p9/300/300",
    stock: 100,
    type: "goods",
  },
  // 일러스트 (r8 - 픽셀덕)
  {
    id: "p10",
    reelId: "r8",
    name: "픽셀아트 아크릴 키링",
    description: "소녀와 여름날 캐릭터를 아크릴 키링으로 제작했습니다. 3cm 크기.",
    price: 2500,
    imageUrl: "https://picsum.photos/seed/p10/300/300",
    stock: 30,
    type: "goods",
  },
  // 도예 (r9 - 아토)
  {
    id: "p11",
    reelId: "r9",
    name: "흙새 미니 도자기 소품",
    description: "아토 작가가 직접 빚은 어린 새 도자기 소품. 세상에 하나뿐입니다.",
    price: 8000,
    imageUrl: "https://picsum.photos/seed/p11/300/300",
    stock: 10,
    type: "original",
  },
  // 도예 (r10 - 도공 김씨)
  {
    id: "p12",
    reelId: "r10",
    name: "손 빚은 소품 그릇 (1개)",
    description: "물레로 빚은 작가의 일상 그릇. 실제 사용 가능한 식기용 유약 처리.",
    price: 15000,
    imageUrl: "https://picsum.photos/seed/p12/300/300",
    stock: 3,
    type: "original",
  },
  {
    id: "p13",
    reelId: "r10",
    name: "도예 입문 온라인 클래스 티켓",
    description: "도공 김씨와 함께하는 물레 체험 클래스. Zoom 라이브 1:1 수업.",
    price: 5000,
    imageUrl: "https://picsum.photos/seed/p13/300/300",
    stock: 999,
    type: "class",
  },
  // 무형예술 (r11 - 해금소녀)
  {
    id: "p14",
    reelId: "r11",
    name: "해금 입문 온라인 클래스 티켓",
    description: "해금소녀와 함께하는 국악 입문 클래스. 악기 없이도 참여 가능.",
    price: 5000,
    imageUrl: "https://picsum.photos/seed/p14/300/300",
    stock: 999,
    type: "class",
  },
  // 무형예술 (r12 - 줄광대)
  {
    id: "p15",
    reelId: "r12",
    name: "줄타기 공연 포스터 프린트 (A3)",
    description: "줄광대의 공연 사진을 아트 포스터로. 사인 포함 한정 수량.",
    price: 3000,
    imageUrl: "https://picsum.photos/seed/p15/300/300",
    stock: 15,
    type: "print",
    },
    {
        id: "p16",
        reelId: "r13",
        name: "His Theme 피아노 악보 (PDF)",
        description: "멜로디 킴이 직접 편곡한 His Theme 연주용 악보입니다.",
        price: 3000,
        imageUrl: "https://picsum.photos/seed/p16/300/300",
        stock: 999,
        type: "goods",
    },
    {
        id: "p17",
        reelId: "r14",
        name: "라캄파넬라 연습 가이드 클래스",
        description: "바이올린 고난도 테크닉을 마스터하기 위한 1:1 온라인 레슨 티켓.",
        price: 30000,
        imageUrl: "https://picsum.photos/seed/p17/300/300",
        stock: 10,
        type: "class",
    },
    {
        id: "p18",
        reelId: "r15",
        name: "핸드메이드 원석 워리스톤",
        description: "손안에 쏙 들어오는 크기의 천연 원석 워리스톤입니다. 랜덤 발송.",
        price: 12000,
        imageUrl: "https://picsum.photos/seed/p18/300/300",
        stock: 25,
        type: "original",
    },
    {
        id: "p19",
        reelId: "r16",
        name: "중세 드레스 제작 패턴 도안",
        description: "발매트를 활용해 만든 드레스의 기초 패턴 PDF 파일입니다.",
        price: 5000,
        imageUrl: "https://picsum.photos/seed/p19/300/300",
        stock: 500,
        type: "goods",
    },
    {
        id: "p20",
        reelId: "r17",
        name: "테라 글라스 업사이클링 목걸이",
        description: "실제 맥주병 유리를 가공하여 만든 영롱한 초록빛 목걸이입니다.",
        price: 28000,
        imageUrl: "https://picsum.photos/seed/p20/300/300",
        stock: 5,
        type: "original",
    },
]
